[platformio]
default_envs = eego_a4_diagnostics

[common]
lib_deps =
  greiman/SdFat @ 2.3.1
  adafruit/Adafruit GFX Library @ 1.12.6

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.mcu = esp32s3
board_build.flash_mode = dio
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.offset_address = 0x10000

build_unflags =
  -std=gnu++11

build_flags =
  -std=gnu++2a
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DFREEINK_DEVICE_EEGO_A4=1
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE=1
  -DUSE_UTF8_LONG_NAMES=1
  -DCORE_DEBUG_LEVEL=1

monitor_filters =
  esp32_exception_decoder
  time

[env:eego_a4_diagnostics]
lib_deps =
  ${common.lib_deps}
  h2zero/NimBLE-Arduino @ 2.5.0
build_src_filter =
  +<*>
  -<../examples/>

[env:eego_a4_quickstart]
lib_deps = ${common.lib_deps}
build_src_filter =
  -<*>
  +<../examples/01_quickstart_display_input/main.cpp>

[env:eego_a4_storage_rtc_battery]
lib_deps = ${common.lib_deps}
build_src_filter =
  -<*>
  +<../examples/02_storage_rtc_battery/main.cpp>

[env:eego_a4_wifi_ble]
lib_deps =
  ${common.lib_deps}
  h2zero/NimBLE-Arduino @ 2.5.0
build_src_filter =
  -<*>
  +<../examples/03_wifi_ble_scan/main.cpp>

[env:eego_a4_safe_sleep]
lib_deps = ${common.lib_deps}
build_src_filter =
  -<*>
  +<../examples/04_safe_deep_sleep/main.cpp>

[env:eego_a4_cpfont]
lib_deps = ${common.lib_deps}
build_src_filter =
  -<*>
  +<../examples/05_cpfont_chinese/main.cpp>
